[workspace]

members = [
  # "esperanto-core",
  "esperanto-javascriptcore",
  "esperanto-quickjs",
  "esperanto-shared",
  "esperanto-ffi",
  "esperanto-jni",
]

[profile.release]
lto = true
opt-level = "s"
panic = 'abort'
