[package]
build = "build.rs"
edition = "2018"
links = "javascriptcore"
name = "esperanto_javascriptcore_sys"
version = "0.1.0"

[build-dependencies]
bindgen = "0.54.1"
cc = {version = "1.0", features = ["parallel"]}
