[package]
edition = "2018"
name = "esperanto_quickjs"
version = "0.1.0"

[dependencies]
esperanto_shared = {path = "../esperanto-shared"}
libquickjs-sys = {path = "../libquickjs-sys"}
slotmap = "0.4.0"
